
const {
    default: makeWASocket,
    useMultiFileAuthState,
    DisconnectReason,
    fetchLatestBaileysVersion,
    makeCacheableSignalKeyStore,
    Browsers
} = require("@whiskeysockets/baileys");
const pino = require("pino");
const { Boom } = require("@hapi/boom");
const readline = require("readline");

// ------------------- RULES (converted from CSV) -------------------
const rules = [
    { pattern: "*hi*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n📢*Hope Your Doing Good*😊\n\n*For any kind of help type (cmd) and send the message bot will reply u*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*www*", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n%name%\n📢*This is your first and Last warning* ⚠️\n\n*Kindly delete that link you have shared in the group if it's not related to hacking stuff or will be removed from the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*bye*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n☛ 𝘽𝙖 𝘽𝙮𝙚 *take care* ☺️\n𝙏𝙖𝙠𝙚 𝙘𝙖𝙧𝙚 𝙙𝙚𝙖𝙧" },
    { pattern: "*hello*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n📢*Hope Your Doing Good*😊\n\n*For any kind of help type (menu) and send the message bot will reply u*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*url*", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n%name%\n📢*This is your first and Last warning* ⚠️\n\n*Kindly delete that link you have shared in the group if it's not related to hacking stuff or will be removed from the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*fuck*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*T*hi*s is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*fuk*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*fck*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n\n┍━━━━━🚫━━━━━┑                                     \n      𝙒𝙖𝙧𝙣𝙞𝙣𝙜⚠️𝙒𝙖𝙧𝙣𝙞𝙣𝙜        \n𝘿𝙚𝙡𝙚𝙩𝙚 𝙩𝙝𝙞𝙨 𝘼𝙗𝙪𝙨𝙞𝙣𝙜 𝙒𝙤𝙧𝙙\n𝙁𝙧𝙤𝙢 𝙩𝙝𝙚 𝙂𝙧𝙤𝙪𝙥 𝙤𝙧 𝙬𝙞𝙡𝙡 𝙗𝙚\n𝙍𝙚𝙢𝙤𝙫𝙚𝙙 𝙛𝙧𝙤𝙢 𝙩𝙝𝙚 𝙜𝙧𝙤𝙪𝙥\n    ┕━━━━━🚫━━━━━┙" },
    { pattern: "*btch*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*bitch*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*sala*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n\n┍━━━━━🚫━━━━━┑                                     \n      𝙒𝙖𝙧𝙣𝙞𝙣𝙜⚠️𝙒𝙖𝙧𝙣𝙞𝙣𝙜        \n𝘿𝙚𝙡𝙚𝙩𝙚 𝙩𝙝𝙞𝙨 𝘼𝙗𝙪𝙨𝙞𝙣𝙜 𝙒𝙤𝙧𝙙\n𝙁𝙧𝙤𝙢 𝙩𝙝𝙚 𝙂𝙧𝙤𝙪𝙥 𝙤𝙧 𝙬𝙞𝙡𝙡 𝙗𝙚\n𝙍𝙚𝙢𝙤𝙫𝙚𝙙 𝙛𝙧𝙤𝙢 𝙩𝙝𝙚 𝙜𝙧𝙤𝙪𝙥\n    ┕━━━━━🚫━━━━━┙" },
    { pattern: "*chutiya*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n--------------------------------------\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*madarchod*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*randi*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n\n┍━━━━━🚫━━━━━┑                                     \n      𝙒𝙖𝙧𝙣𝙞𝙣𝙜⚠️𝙒𝙖𝙧𝙣𝙞𝙣𝙜        \n𝘿𝙚𝙡𝙚𝙩𝙚 𝙩𝙝𝙞𝙨 𝘼𝙗𝙪𝙨𝙞𝙣𝙜 𝙒𝙤𝙧𝙙\n𝙁𝙧𝙤𝙢 𝙩𝙝𝙚 𝙂𝙧𝙤𝙪𝙥 𝙤𝙧 𝙬𝙞𝙡𝙡 𝙗𝙚\n𝙍𝙚𝙢𝙤𝙫𝙚𝙙 𝙛𝙧𝙤𝙢 𝙩𝙝𝙚 𝙜𝙧𝙤𝙪𝙥\n    ┕━━━━━🚫━━━━━┙" },
    { pattern: "*bsdk*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*behenchod*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*laura*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*nigga*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*tere maa*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "help", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n📢*Hope Your Doing Good*😊\n\n*So sorry 😞 but At this point of time non of the Admins are online to reply*\n*But will definitely reply your message once they are online ☺️*\n\n👇👇👇👇👇👇👇👇👇👇👇\n*For any kind of help type (menu) and send the message bot will reply u*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "please help", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n📢*Hope Your Doing Good*😊\n\n*So sorry 😞 but At this point of time non of the Admins are online to reply*\n*But will definitely reply your message once they are online ☺️*\n\n👇👇👇👇👇👇👇👇👇👇👇\n*For any kind of help type (menu) and send the message bot will reply u*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*start*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n🤖This Is Hackers colony Bot im On Ready" },
    { pattern: "*stop*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n🤖 *Im Hackers colony Bot*\n*Im Turning Off* 📴\n*Ba bye* ☺️" },
    { pattern: "*suck*", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*T*hi*s is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "thank you", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*You are Most welcome Buddy* 🤗" },
    { pattern: "tnx", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Anytime for You Brother* 🤗" },
    { pattern: "tq", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*You are Most welcome Buddy* 🤗" },
    { pattern: "*thanks*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*You are Most welcome Buddy* 🤗" },
    { pattern: "tq sir", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\nAnytime %name% 😇" },
    { pattern: "*hi*i", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n📢*Hope Your Doing Good*😊\n\n*For any kind of help type (menu) and send the message bot will reply u*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*ok*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\nSure.....😇" },
    { pattern: "*👾 gif*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n\n┍━━━━━🚫━━━━━┑\n   ⚠️ *WARNING* ⚠️\n\n    DELETE THE GIF\n\n       *_GIFS BANNED_*\n┕━━━━━🚫━━━━━┙\n\n\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝗧𝗲𝗮𝗺\n𝗛𝗖𝗢 𝗔𝗱𝗺𝗶𝗻𝘀😊" },
    { pattern: "*🎤 voice message*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n\nWarning ⚠️⚠️⚠️⚠️⚠️⚠️⚠️\n🤖No audio in the group Please,.....\n\n\n******************************\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝗧𝗲𝗮𝗺\n𝗛𝗖𝗢 𝗔𝗱𝗺𝗶𝗻𝘀😊" },
    { pattern: "*🎥 video*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n🤖No, videos in the group please\n\n\n\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝗧𝗲𝗮𝗺\n𝗛𝗖𝗢 𝗔𝗱𝗺𝗶𝗻𝘀😊" },
    { pattern: "*📷 images*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n𝗪𝗵𝗮𝘁 𝗶𝘀 𝘁𝗵𝗲 𝗶𝘀𝘀𝘂𝗲 𝘄𝗶𝘁𝗵 𝘁𝗵𝗶𝘀 𝗹𝗲𝘁 𝘂𝘀 𝗸𝗻𝗼𝘄 𝗼𝗻𝗲 𝗼𝗳 𝘁𝗵𝗲 𝗮𝗱𝗺𝗶𝗻 𝘄𝗶𝗹𝗹 𝘁𝗿𝘆 𝘁𝗼 𝗳𝗶𝘅 𝗼𝗿 𝗵𝗲𝗹𝗽 𝘆𝗼𝘂\n\n******************************\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝗧𝗲𝗮𝗺\n𝗛𝗖𝗢 𝗔𝗱𝗺𝗶𝗻𝘀😊" },
    { pattern: "*https:*", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n%name%\n📢*T*hi*s is your first and Last warning* ⚠️\n\n*Kindly delete that link you have shared in the group if it's not related to hacking stuff or will be removed from the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*mc//bc//bsdk//muh//chutiye*", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*T*hi*s is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "bot", reply: "*hi*, hai brother\n\n𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n*HEY, BROTHER*\n*IM HCO BOT 🤖 Im ONN USE IT BY TYPING Menu*<#>*𝗕𝗢𝗧 𝗧𝗜𝗠𝗜𝗡𝗚𝗦*\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*⏳ -> [𝗢𝗡] 𝗠𝗢𝗥𝗡𝗜𝗡𝗚 Active*\n*⌛ -> [𝗢𝗙𝗙] 𝗡𝗜𝗚𝗛𝗧 Active*\n\n*𝗛𝗔𝗩𝗘 𝗔 𝗚𝗢𝗢𝗗 𝗗𝗔𝗬*" },
    { pattern: "*📄*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n┍━━━━━🚫━━━━━┑\n   ⚠️ *WARNING* ⚠️\n\n  DELETE THE DOC\n             \n   *_DOCUMENTS BANNED_*\n┕━━━━━🚫━━━━━┙\n\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝗧𝗲𝗮𝗺\n𝗛𝗖𝗢 𝗔𝗱𝗺𝗶𝗻𝘀😊" },
    { pattern: "rules", reply: "*hi*, hai brother\n\n*I'm Hackers Colony Bot🤖Replying on behalf of the Admins*\n\n👇👇👇👇👇👇👇👇👇👇\n********************************\n🚨𝗚𝗿𝗼𝘂𝗽 𝗥𝘂𝗹𝗲𝘀📢\n\n*NO Spamming in the group*\n*No Advertising in the group*\n*No Selling in the group*\n*No Promotion in the group* \n*No Sharing of Links*\n*No Sharing of Video*\n*No Sharing of Audio*\n*Do not dm anyone without permission*\n*Respect every person in the group*\n*Don't argue or fight in the group for silly stuff*\n\n*Anyone Breaking Rules in the group will be kicked out and banned permanently* 🚫\n\n*If anything serious contact any admin directly* 💢\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝗳𝗼𝗿 𝗷𝗼𝗶𝗻𝗶𝗻𝗴 𝗼𝘂𝗿 𝗴𝗿𝗼𝘂𝗽\n\n𝗧𝗲𝗮𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 🔖" },
    { pattern: "routersploit", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝐇𝐨𝐰 𝐭𝐨 𝐈𝐧𝐬𝐭𝐚𝐥𝐥 𝐑𝐨𝐮𝐭𝐞𝐫𝐬𝐩𝐥𝐨𝐢𝐭 𝐨𝐫 𝐇𝐨𝐰 𝐭𝐨 𝐇𝐚𝐜𝐤 𝐖𝐢𝐟𝐢 𝐢𝐧 𝐓𝐞𝐫𝐦𝐮𝐱 𝐢𝐧 𝐣𝐮𝐬𝐭 𝟒 𝐞𝐚𝐬𝐲 𝐬𝐭𝐞𝐩𝐬 𝐯𝐢𝐝𝐞𝐨 𝐥𝐢𝐧𝐤 𝐛𝐞𝐥𝐨𝐰 🔁\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-\nhttps://youtu.be/zqNtEu0upVw\nhttps://youtu.be/zqNtEu0upVw" },
    { pattern: "*hack wifi*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙃𝙤𝙬 𝙩𝙤 𝙃𝙖𝙘𝙠 𝙒𝙞𝙛𝙞 𝙞𝙣 𝙏𝙚𝙧𝙢𝙪𝙭 𝙪𝙨𝙞𝙣𝙜 𝙍𝙤𝙪𝙩𝙚𝙧𝙨𝙥𝙡𝙤𝙞𝙩 𝙞𝙣 𝙟𝙪𝙨𝙩 4 𝙚𝙖𝙨𝙮 𝙨𝙩𝙚𝙥𝙨 𝙫𝙞𝙙𝙚𝙤 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 🔁\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-__-_-_-_-_-_\nhttps://youtu.be/zqNtEu0upVw\nhttps://youtu.be/zqNtEu0upVw" },
    { pattern: "*whatsapp malware*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙒𝙝𝙖𝙩𝙨𝘼𝙥𝙥 𝙃𝙖𝙘𝙠𝙚𝙙♂️ 𝙒𝙝𝙖𝙩𝙨𝘼𝙥𝙥 𝙈𝙖𝙡𝙬𝙖𝙧𝙚 𝙛𝙤𝙧 𝘼𝙣𝙙𝙧𝙤𝙞𝙙\n𝙫𝙞𝙙𝙚𝙤 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 🔁\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n_-_-_-_-_-_-__-_-_-_-_-_-_-__-_-_-_-__-_\nhttps://youtu.be/SU7DED9acwA\nhttps://youtu.be/SU7DED9acwA" },
    { pattern: "whatsapp virus", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙒𝙝𝙖𝙩𝙨𝘼𝙥𝙥 𝙃𝙖𝙘𝙠𝙚𝙙♂️ 𝙒𝙝𝙖𝙩𝙨𝘼𝙥𝙥 𝙈𝙖𝙡𝙬𝙖𝙧𝙚 𝙛𝙤𝙧 𝘼𝙣𝙙𝙧𝙤𝙞𝙙\n𝙫𝙞𝙙𝙚𝙤 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 🔁\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n_-_-_-_-_-_-__-_-_-_-_-_-_-__-_-_-_-__-_\nhttps://fb.watch/cuhjvAn5Sa/" },
    { pattern: "*video*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙒𝙚𝙡𝙘𝙤𝙢𝙚 𝙩𝙤 𝙤𝙪𝙧 𝘾𝙝𝙖𝙣𝙣𝙚𝙡 💕💕\n➖➖➖➖➖➖➖➖➖➖➖➖\n𝙔𝙤𝙪 𝙘𝙖𝙣 𝙬𝙖𝙩𝙘𝙝 𝙤𝙪𝙧 𝙖𝙡𝙡 𝙝𝙖𝙘𝙠𝙞𝙣𝙜 𝙫𝙞𝙙𝙚𝙤𝙨.\n𝙃𝙚𝙧𝙚 𝙞𝙣 𝙤𝙪𝙧 𝙘𝙝𝙖𝙣𝙣𝙚𝙡 𝙬𝙞𝙩𝙝 𝙟𝙪𝙨𝙩 𝙤𝙣𝙚 𝙩𝙖𝙥\n𝘾𝙡𝙞𝙘𝙠 𝙤𝙣 𝙩𝙝𝙚 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 𝙩𝙤 𝙫𝙞𝙨𝙞𝙩 𝙤𝙪𝙧 𝙘𝙝𝙖𝙣𝙣𝙚𝙡\n📛📛📛📛📛📛📛📛📛📛📛📛📛\n➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗦𝗼 𝗴𝘂𝘆𝘀 𝘄𝗵𝗲𝗻 𝘆𝗼𝘂 𝘄𝗮𝘁𝗰𝗵 𝗼𝘂𝗿 𝘃𝗶𝗱𝗲𝗼'𝘀 𝗱𝗼 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝘂𝘀 𝘄𝗶𝘁𝗵 𝘆𝗼𝘂𝗿 𝗹𝗶𝗸𝗲 𝘀𝘂𝗯𝘀𝗰𝗿𝗶𝗯𝗲 𝗰𝗼𝗺𝗺𝗲𝗻𝘁𝘀 𝗮𝗻𝗱 𝗵𝗶𝘁 𝗶𝗻 𝗯𝗲𝗹𝗹 🔔 𝗶𝗰𝗼𝗻\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟭🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗢𝗳𝗳𝗶𝗰𝗶𝗮𝗹\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\n𝗵𝘁𝘁𝗽𝘀://𝘆𝗼𝘂𝘁𝘂𝗯𝗲.𝗰𝗼𝗺/𝗰𝗵𝗮𝗻𝗻𝗲𝗹/𝗨𝗖𝗫𝗻𝗕𝗭𝗥𝗽𝗟𝗗𝟳𝗤𝘇𝗰𝗝𝘀𝗨𝗞𝗕𝗙-𝗰𝗞𝘄\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟮🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗧𝗲𝗰𝗵\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\n𝗵𝘁𝘁𝗽𝘀://𝘆𝗼𝘂𝘁𝘂𝗯𝗲.𝗰𝗼𝗺/𝗰𝗵𝗮𝗻𝗻𝗲𝗹/𝗨𝗖𝗘𝗲𝘆𝟰𝗞𝗣𝗪𝗾𝗪𝗚𝗚𝗸𝘁𝗯𝟰𝗠𝗲𝟴𝗲𝘅𝗲𝗔\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟯🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\n𝗵𝘁𝘁𝗽𝘀://𝘆𝗼𝘂𝘁𝘂𝗯𝗲.𝗰𝗼𝗺/𝗰𝗵𝗮𝗻𝗻𝗲𝗹/𝗨𝗖𝗱𝗼𝗪𝗯𝗣𝟱𝗧𝗺𝗾𝗻𝗿𝗯𝗽𝗲𝗻𝗧𝗙𝟳𝗻𝗽𝗦𝗔\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗧𝗵𝗮𝗻𝗸 𝗮𝗻𝗱 𝗥𝗲𝗴𝗮𝗿𝗱𝘀\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗧𝗲𝗮𝗺\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝐕𝐢𝐬𝐢𝐭 𝐨𝐮𝐫 𝐰𝐞𝐛𝐬𝐢𝐭𝐞 𝐟𝐨𝐫 𝐚𝐝𝐯𝐚𝐧𝐜𝐞 𝐡𝐚𝐜𝐤𝐢𝐧𝐠 \n𝐬𝐭𝐮𝐟𝐟𝐬 𝐚𝐧𝐝 𝐓𝐞𝐫𝐦𝐮𝐱 𝐂𝐨𝐦𝐦𝐚𝐧𝐝𝐬\n📛📛📛📛\nwww.hackerscolonyofficial.blogspot.com" },
    { pattern: "channel link", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙒𝙚𝙡𝙘𝙤𝙢𝙚 𝙩𝙤 𝙤𝙪𝙧 𝘾𝙝𝙖𝙣𝙣𝙚𝙡 💕💕\n➖➖➖➖➖➖➖➖➖➖➖➖\n𝙔𝙤𝙪 𝙘𝙖𝙣 𝙬𝙖𝙩𝙘𝙝 𝙤𝙪𝙧 𝙖𝙡𝙡 𝙝𝙖𝙘𝙠𝙞𝙣𝙜 𝙫𝙞𝙙𝙚𝙤𝙨.\n𝙃𝙚𝙧𝙚 𝙞𝙣 𝙤𝙪𝙧 𝙘𝙝𝙖𝙣𝙣𝙚𝙡 𝙬𝙞𝙩𝙝 𝙟𝙪𝙨𝙩 𝙤𝙣𝙚 𝙩𝙖𝙥\n𝘾𝙡𝙞𝙘𝙠 𝙤𝙣 𝙩𝙝𝙚 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 𝙩𝙤 𝙫𝙞𝙨𝙞𝙩 𝙤𝙪𝙧 𝙘𝙝𝙖𝙣𝙣𝙚𝙡\n📛📛📛📛📛📛📛📛📛📛📛📛📛\n➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟭🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗢𝗳𝗳𝗶𝗰𝗶𝗮𝗹\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\nhttps://youtube.com/channel/UCXnBZRpLD7QzcJsUKBF-cKw\n➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟮🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗧𝗲𝗰𝗵\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\nhttps://youtube.com/channel/UCEey4KPWqWGGktb4Me8exeA\n➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟯🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\nhttps://youtube.com/channel/UCdoWbP5TmqnrbpenTF7npSA\n➖➖➖➖➖➖➖➖➖➖➖\n𝗧𝗵𝗮𝗻𝗸 𝗮𝗻𝗱 𝗥𝗲𝗴𝗮𝗿𝗱𝘀\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗧𝗲𝗮𝗺\n➖➖➖➖➖➖➖➖➖➖➖\n𝐕𝐢𝐬𝐢𝐭 𝐨𝐮𝐫 𝐰𝐞𝐛𝐬𝐢𝐭𝐞 𝐟𝐨𝐫 𝐚𝐝𝐯𝐚𝐧𝐜𝐞 𝐡𝐚𝐜𝐤𝐢𝐧𝐠 \n𝐬𝐭𝐮𝐟𝐟𝐬 𝐚𝐧𝐝 𝐓𝐞𝐫𝐦𝐮𝐱 𝐂𝐨𝐦𝐦𝐚𝐧𝐝𝐬\n📛📛📛📛\nwww.hackerscolonyofficial.blogspot.com" },
    { pattern: "dictionary attack", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗼𝘄 𝘁𝗼 𝗽𝗲𝗿𝗳𝗼𝗿𝗺 𝗗𝗶𝗰𝘁𝗶𝗼𝗻𝗮𝗿𝘆 𝗮𝘁𝘁𝗮𝗰𝗸 𝗖𝗼𝗺𝗺𝗮𝗻𝗱.\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\n🤖Follow this command to do dictionary attack 😃\n---------------------------------------\n~ git clone --depth=1 --branch=master https://www.github.com/landgrey/pydictor.git \n\n~ cd pydictor\n\n~ chmod +x pydictor.py \n\n~ python pydictor.py" },
    { pattern: "how to hack gmail", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙃𝙤𝙬 𝙩𝙤 𝙝𝙖𝙘𝙠 𝙂𝙢𝙖𝙞𝙡 𝘼𝙘𝙘𝙤𝙪𝙣𝙩😉\n𝘾𝙡𝙞𝙘𝙠 𝙤𝙣 𝙩𝙝𝙚 𝙡𝙞𝙣𝙠 𝙩𝙤 𝙬𝙖𝙩𝙘𝙝 𝙩𝙝𝙚 𝙫𝙞𝙙𝙚𝙤 𝙤𝙣 𝙝𝙤𝙬 𝙩𝙤 𝙝𝙖𝙘𝙠 𝙂𝙢𝙖𝙞𝙡 𝘼𝙘𝙘𝙤𝙪𝙣𝙩😃\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\nhttps://hackerscolonyofficial.blogspot.com/2021/03/how-to-hack-gmail-using-easy-hack.html?m=1" },
    { pattern: "gmail hack", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n**********************************\n*Want to Get a Gmail Password or want to Hack anyone's Gmail password 🔑 😈 then check the video below link given below 👇🏼*\n-----------------------------------------------\nhttps://youtu.be/MlNrxlhuqXQ" },
    { pattern: "*otp bypass*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n******************************\n𝗕𝘆𝗽𝗮𝘀𝘀 𝗢𝗧𝗣 𝗳𝗼𝗿 𝗮𝗻𝘆𝘁𝗵𝗶𝗻𝗴 𝘂𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅 𝗶𝗻 𝗺𝗼𝘀𝘁 𝗲𝗮𝘀𝘆 𝘄𝗮𝘆\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n******************************\nhttps://youtu.be/exxBhel2Bos" },
    { pattern: "*bypass otp*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗕𝘆𝗽𝗮𝘀𝘀 𝗢𝗧𝗣 𝗳𝗼𝗿 𝗮𝗻𝘆𝘁𝗵𝗶𝗻𝗴 𝘂𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅 𝗶𝗻 𝗺𝗼𝘀𝘁 𝗲𝗮𝘀𝘆 𝘄𝗮𝘆\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\nhttps://hackerscolonyofficial.blogspot.com/2021/02/otp-bypass-in-termux-android.html?m=1" },
    { pattern: "*how to hack website*", reply: "𝙃𝙖𝙘𝙠 𝙖𝙣𝙮 𝙬𝙚𝙗𝙨𝙞𝙩𝙚 𝙪𝙨𝙞𝙣𝙜 𝙔𝙤𝙪𝙧 𝘼𝙣𝙙𝙧𝙤𝙞𝙙 𝙥𝙝𝙤𝙣𝙚 𝙤𝙧 𝘾𝙤𝙢𝙥𝙪𝙩𝙚𝙧 𝙞𝙣 𝙚𝙖𝙨𝙮 𝙬𝙖𝙮🤩\n𝘾𝙡𝙞𝙘𝙠 𝙤𝙣 𝙩𝙝𝙚 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 𝙩𝙤 𝙬𝙖𝙩𝙘𝙝 𝙩𝙝𝙚 𝙫𝙞𝙙𝙚𝙤🤩\n---------------------------------------------------\nhttps://www.facebook.com/1987580371566058/videos/4210170685677495/" },
    { pattern: "*hack website*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙃𝙖𝙘𝙠 𝙖𝙣𝙮 𝙬𝙚𝙗𝙨𝙞𝙩𝙚 𝙪𝙨𝙞𝙣𝙜 𝙔𝙤𝙪𝙧 𝘼𝙣𝙙𝙧𝙤𝙞𝙙 𝙥𝙝𝙤𝙣𝙚 𝙤𝙧 𝘾𝙤𝙢𝙥𝙪𝙩𝙚𝙧 𝙞𝙣 𝙚𝙖𝙨𝙮 𝙬𝙖𝙮🤩\n𝘾𝙡𝙞𝙘𝙠 𝙤𝙣 𝙩𝙝𝙚 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 𝙩𝙤 𝙬𝙖𝙩𝙘𝙝 𝙩𝙝𝙚 𝙫𝙞𝙙𝙚𝙤🤩\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\nhttps://www.facebook.com/1987580371566058/videos/4210170685677495/" },
    { pattern: "*website hacking*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙃𝙖𝙘𝙠 𝙖𝙣𝙮 𝙬𝙚𝙗𝙨𝙞𝙩𝙚 𝙪𝙨𝙞𝙣𝙜 𝙔𝙤𝙪𝙧 𝘼𝙣𝙙𝙧𝙤𝙞𝙙 𝙥𝙝𝙤𝙣𝙚 𝙤𝙧 𝘾𝙤𝙢𝙥𝙪𝙩𝙚𝙧 𝙞𝙣 𝙚𝙖𝙨𝙮 𝙬𝙖𝙮🤩\n𝘾𝙡𝙞𝙘𝙠 𝙤𝙣 𝙩𝙝𝙚 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 𝙩𝙤 𝙬𝙖𝙩𝙘𝙝 𝙩𝙝𝙚 𝙫𝙞𝙙𝙚𝙤🤩\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\nhttps://www.facebook.com/1987580371566058/videos/4210170685677495/" },
    { pattern: "how to hack iphone", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗣𝗵𝗼𝗻𝗲 𝗨𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅 𝗶𝗻 𝗠𝗼𝘀𝘁 𝗲𝗮𝘀𝘆 𝘄𝗮𝘆\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\nhttps://www.facebook.com/1987580371566058/videos/4210170685677495/" },
    { pattern: "*android hacking*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗣𝗵𝗼𝗻𝗲 𝗨𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅 𝗶𝗻 𝗠𝗼𝘀𝘁 𝗲𝗮𝘀𝘆 𝘄𝗮𝘆\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\nhttps://www.facebook.com/1987580371566058/videos/4210170685677495/" },
    { pattern: "*ip hack*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗽𝗵𝗼𝗻𝗲 𝘂𝘀𝗶𝗻𝗴 𝗜𝗣 𝗮𝗱𝗱𝗿𝗲𝘀𝘀 𝘂𝘀𝗶𝗻𝗴 𝗣𝗵𝗼𝗻𝗲𝗦𝗽𝗼𝗹𝗶𝘁 𝗶𝗻 𝗧𝗲𝗿𝗺𝘂𝘅\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\nhttps://youtu.be/e7ogIDP5BPg" },
    { pattern: "*Bruteforce attack*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n*👇BrutXInsta Powerful Bruteforce Attack tool to find instagram Password*\n\n*To Run this to install the Tool follow the command given below 👇🏼 👇🏼*\n\n𝟭. 𝗽𝗸𝗴 𝘂𝗽𝗱𝗮𝘁𝗲\n\n𝟮. 𝗽𝗸𝗴 𝘂𝗽𝗴𝗿𝗮𝗱𝗲 -𝘆\n\n𝟯. 𝗽𝗸𝗴 𝗶𝗻𝘀𝘁𝗮𝗹𝗹 𝗴𝗶𝘁 -𝘆\n\n𝟰. 𝗴𝗶𝘁 𝗰𝗹𝗼𝗻𝗲 https://github.com/Hackerscolonyofficial/BrutXInsta.git\n\n𝟱. 𝗰𝗱 𝗕𝗿𝘂𝘁𝗫𝗜𝗻𝘀𝘁𝗮\n\n𝟲. 𝗹𝘀\n\n𝟳. 𝗰𝗵𝗺𝗼𝗱 +𝘅 *\n\n𝟴. 𝗯𝗮𝘀𝗵 𝘀𝘁𝗮𝗿𝘁.𝘀𝗵\n\nusername entar of the persons id you want acess)\n\nwordilst passilst).......\n\n*Thank you* 😃\n*Team HCO*" },
    { pattern: "*zp*hi*sher*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\nInstall Zphisher using this command in your termux\n\napt update\n\napt upgrade\n\napt install git \n\nphp openssh curl -y\n\ngit clone https://github.com/htr-tech/zphisher\n\ncd zphisher\n\nchmod +x zphisher.sh \n\nbash zphisher.sh" },
    { pattern: "instagram account ban", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗼𝘄 𝘁𝗼 𝗥𝗲𝗽𝗼𝗿𝘁 𝗗𝗲𝗹𝗲𝘁𝗲 𝗼𝗿 𝗕𝗮𝗻 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗮𝗰𝗰𝗼𝘂𝗻𝘁\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://www.instagram.com/tv/CQpPE8DF2mu/?utm_medium=copy_link" },
    { pattern: "report instagram account", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗼𝘄 𝘁𝗼 𝗥𝗲𝗽𝗼𝗿𝘁 𝗗𝗲𝗹𝗲𝘁𝗲 𝗼𝗿 𝗕𝗮𝗻 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗮𝗰𝗰𝗼𝘂𝗻𝘁\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://www.instagram.com/tv/CQpPE8DF2mu/?utm_medium=copy_link" },
    { pattern: "*How to Delete Instagram account*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗼𝘄 𝘁𝗼 𝗥𝗲𝗽𝗼𝗿𝘁 𝗗𝗲𝗹𝗲𝘁𝗲 𝗼𝗿 𝗕𝗮𝗻 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗮𝗰𝗰𝗼𝘂𝗻𝘁\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://www.instagram.com/tv/CQpPE8DF2mu/?utm_medium=copy_link" },
    { pattern: "root termux", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n*Get ROOT access in Termux and run Tools without Rooting Phone Risk Free Rooting Access🤩*\n\n*Watch video below to know how to root access*\n\nhttps://youtu.be/WCwOhcLFxSA" },
    { pattern: "payload", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗖𝗿𝗲𝗮𝘁𝗲 𝘆𝗼𝘂𝗿 𝗼𝘄𝗻 𝗣𝗮𝘆𝗹𝗼𝗮𝗱 𝗨𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅 🤩 \nBang anyone's android phone 📱\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://fb.watch/bOy6hrzwxR/" },
    { pattern: "How to make payload", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗖𝗿𝗲𝗮𝘁𝗲 𝘆𝗼𝘂𝗿 𝗼𝘄𝗻 𝗣𝗮𝘆𝗹𝗼𝗮𝗱 𝗨𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅 🤩\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://fb.watch/bOy6hrzwxR/" },
    { pattern: "instagram hacking", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸, 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺, 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽, 𝗦𝗻𝗮𝗽𝗖𝗵𝗮𝘁 𝗮𝗻𝗱 𝗠𝗼𝗿𝗲 𝘂𝘀𝗶𝗻𝗴 𝗛𝗖𝗢-𝗣𝗵𝗶𝘀𝗵𝗲𝗿🦈\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://fb.watch/ct4ZvgnpoM/" },
    { pattern: "Snapchat hacking", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸, 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺, 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽, 𝗦𝗻𝗮𝗽𝗖𝗵𝗮𝘁 𝗮𝗻𝗱 𝗠𝗼𝗿𝗲 𝘂𝘀𝗶𝗻𝗴 𝘁𝗵𝗶𝘀 𝗛𝗖𝗢-𝗣𝗵𝗶𝘀𝗵𝗲𝗿 🦈\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://www.facebook.com/1987580371566058/posts/3260475117609904/" },
    { pattern: "facebook/instagram/whatsapp/telegram/phonepe/", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸, 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺, 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽, 𝗦𝗻𝗮𝗽𝗖𝗵𝗮𝘁 𝗮𝗻𝗱 𝗠𝗼𝗿𝗲 𝘂𝘀𝗶𝗻𝗴 𝘁𝗵𝗶𝘀 𝗛𝗖𝗢-𝗣𝗵𝗶𝘀𝗵𝗲𝗿 🦈\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://fb.watch/ct4ZvgnpoM/" },
    { pattern: "instagram hack", reply: "hi, hai brother\n\n𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀👬\n********************************\n📢📢 *Want to Hack* \n🔥 *Instagram*\n🔥 *Facebook*\n🔥 *Snapchat*\n🔥 *Telegram*\n*And many more do Check out* 👇🏼👇🏼👇🏼\nhttps://youtu.be/_fC0Eju8uMo" },
    { pattern: "Hack Telegram", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸, 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺, 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽, 𝗦𝗻𝗮𝗽𝗖𝗵𝗮𝘁 𝗮𝗻𝗱 𝗠𝗼𝗿𝗲 𝘂𝘀𝗶𝗻𝗴 𝘁𝗵𝗶𝘀 𝗛𝗖𝗢-𝗣𝗵𝗶𝘀𝗵𝗲𝗿 🦈\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://fb.watch/ct4ZvgnpoM/" },
    { pattern: "install ngrok", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗜𝗻𝘀𝘁𝗮𝗹𝗹 𝗡𝗴𝗿𝗼𝗸 𝗶𝗻 𝗧𝗲𝗿𝗺𝘂𝘅 𝗪𝗶𝘁𝗵𝗼𝘂𝘁 𝗥𝗼𝗼𝘁 𝗶𝗻 𝗺𝗼𝘀𝘁 𝗲𝗮𝘀𝘆 𝘄𝗮𝘆\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n********************************\nhttps://fb.watch/bOz6eBZcHF/" },
    { pattern: "*PhoneSpolit*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗽𝗵𝗼𝗻𝗲 𝘂𝘀𝗶𝗻𝗴 𝗜𝗣 𝗮𝗱𝗱𝗿𝗲𝘀𝘀 𝘂𝘀𝗶𝗻𝗴 𝗣𝗵𝗼𝗻𝗲𝗦𝗽𝗼𝗹𝗶𝘁 𝗶𝗻 𝗧𝗲𝗿𝗺𝘂𝘅\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n*********************************\nhttps://youtu.be/e7ogIDP5BPg" },
    { pattern: "*group rules*", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot🤖Replying on behalf of the Admins*\n\n👇👇👇👇👇👇👇👇👇👇\n********************************\n🚨𝗚𝗿𝗼𝘂𝗽 𝗥𝘂𝗹𝗲𝘀📢\n\n*NO Spamming in the group*\n*No Advertising in the group*\n*No Selling in the group*\n*No Promotion in the group* \n*No Sharing of Links*\n*No Sharing of Video*\n*No Sharing of Audio*\n*Do not dm anyone without permission*\n*Respect every person in the group*\n*Don't argue or fight in the group for silly stuff*\n\n*Anyone Breaking Rules in the group will be kicked out and banned permanently* 🚫\n\n*If anything serious contact any admin directly* 💢\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝗳𝗼𝗿 𝗷𝗼𝗶𝗻𝗶𝗻𝗴 𝗼𝘂𝗿 𝗴𝗿𝗼𝘂𝗽\n\n𝗧𝗲𝗮𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 🔖" },
    { pattern: "*youtube*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝙒𝙚𝙡𝙘𝙤𝙢𝙚 𝙩𝙤 𝙤𝙪𝙧 𝘾𝙝𝙖𝙣𝙣𝙚𝙡 💕💕\n➖➖➖➖➖➖➖➖➖➖➖➖\n𝙔𝙤𝙪 𝙘𝙖𝙣 𝙬𝙖𝙩𝙘𝙝 𝙤𝙪𝙧 𝙖𝙡𝙡 𝙝𝙖𝙘𝙠𝙞𝙣𝙜 𝙫𝙞𝙙𝙚𝙤𝙨.\n𝙃𝙚𝙧𝙚 𝙞𝙣 𝙤𝙪𝙧 𝙘𝙝𝙖𝙣𝙣𝙚𝙡 𝙬𝙞𝙩𝙝 𝙟𝙪𝙨𝙩 𝙤𝙣𝙚 𝙩𝙖𝙥\n𝘾𝙡𝙞𝙘𝙠 𝙤𝙣 𝙩𝙝𝙚 𝙡𝙞𝙣𝙠 𝙗𝙚𝙡𝙤𝙬 𝙩𝙤 𝙫𝙞𝙨𝙞𝙩 𝙤𝙪𝙧 𝙘𝙝𝙖𝙣𝙣𝙚𝙡\n📛📛📛📛📛📛📛📛📛📛📛📛📛\n➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗦𝗼 𝗴𝘂𝘆𝘀 𝘄𝗵𝗲𝗻 𝘆𝗼𝘂 𝘄𝗮𝘁𝗰𝗵 𝗼𝘂𝗿 𝘃𝗶𝗱𝗲𝗼'𝘀 𝗱𝗼 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝘂𝘀 𝘄𝗶𝘁𝗵 𝘆𝗼𝘂𝗿 𝗹𝗶𝗸𝗲 𝘀𝘂𝗯𝘀𝗰𝗿𝗶𝗯𝗲 𝗰𝗼𝗺𝗺𝗲𝗻𝘁𝘀 𝗮𝗻𝗱 𝗵𝗶𝘁 𝗶𝗻 𝗯𝗲𝗹𝗹 🔔 𝗶𝗰𝗼𝗻\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟭🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗢𝗳𝗳𝗶𝗰𝗶𝗮𝗹\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\n𝗵𝘁𝘁𝗽𝘀://𝘆𝗼𝘂𝘁𝘂𝗯𝗲.𝗰𝗼𝗺/𝗰𝗵𝗮𝗻𝗻𝗲𝗹/𝗨𝗖𝗫𝗻𝗕𝗭𝗥𝗽𝗟𝗗𝟳𝗤𝘇𝗰𝗝𝘀𝗨𝗞𝗕𝗙-𝗰𝗞𝘄\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟮🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗧𝗲𝗰𝗵\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\n𝗵𝘁𝘁𝗽𝘀://𝘆𝗼𝘂𝘁𝘂𝗯𝗲.𝗰𝗼𝗺/𝗰𝗵𝗮𝗻𝗻𝗲𝗹/𝗨𝗖𝗘𝗲𝘆𝟰𝗞𝗣𝗪𝗾𝗪𝗚𝗚𝗸𝘁𝗯𝟰𝗠𝗲𝟴𝗲𝘅𝗲𝗔\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗻𝗼 𝟯🤩\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆\n\n𝗖𝗵𝗮𝗻𝗻𝗲𝗹 𝗹𝗶𝗻𝗸 👇👇👇\n𝗵𝘁𝘁𝗽𝘀://𝘆𝗼𝘂𝘁𝘂𝗯𝗲.𝗰𝗼𝗺/𝗰𝗵𝗮𝗻𝗻𝗲𝗹/𝗨𝗖𝗱𝗼𝗪𝗯𝗣𝟱𝗧𝗺𝗾𝗻𝗿𝗯𝗽𝗲𝗻𝗧𝗙𝟳𝗻𝗽𝗦𝗔\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝗧𝗵𝗮𝗻𝗸 𝗮𝗻𝗱 𝗥𝗲𝗴𝗮𝗿𝗱𝘀\n𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗧𝗲𝗮𝗺\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n𝐕𝐢𝐬𝐢𝐭 𝐨𝐮𝐫 𝐰𝐞𝐛𝐬𝐢𝐭𝐞 𝐟𝐨𝐫 𝐚𝐝𝐯𝐚𝐧𝐜𝐞 𝐡𝐚𝐜𝐤𝐢𝐧𝐠 \n𝐬𝐭𝐮𝐟𝐟𝐬 𝐚𝐧𝐝 𝐓𝐞𝐫𝐦𝐮𝐱 𝐂𝐨𝐦𝐦𝐚𝐧𝐝𝐬\n📛📛📛📛\nwww.hackerscolonyofficial.blogspot.com" },
    { pattern: "phishing command", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗪𝗮𝘁𝗰𝗵 𝘁𝗵𝗲 𝘃𝗶𝗱𝗲𝗼 𝗯𝗲𝗹𝗼𝘄 𝘁𝗼 𝗣𝗲𝗿𝗳𝗼𝗿𝗺 𝗣𝗵𝗶𝘀𝗵𝗶𝗻𝗴 𝗔𝘁𝘁𝗮𝗰𝗸 𝘁𝗼 𝗵𝗮𝗰𝗸 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸, 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗮𝗻𝗱 𝗠𝗼𝗿𝗲\n********************************\n⏬           ⏬            ⏬            ⏬\nhttps://fb.watch/bODBWRQe24/" },
    { pattern: "*Phishing*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗪𝗮𝘁𝗰𝗵 𝘁𝗵𝗲 𝘃𝗶𝗱𝗲𝗼 𝗯𝗲𝗹𝗼𝘄 𝘁𝗼 𝗣𝗲𝗿𝗳𝗼𝗿𝗺 𝗣𝗵𝗶𝘀𝗵𝗶𝗻𝗴 𝗔𝘁𝘁𝗮𝗰𝗸 𝘁𝗼 𝗵𝗮𝗰𝗸 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸, 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗮𝗻𝗱 𝗠𝗼𝗿𝗲\n********************************\n⏬           ⏬            ⏬            ⏬\nhttps://fb.watch/ct4ZvgnpoM/" },
    { pattern: "*fake number*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n*Create a fake WhatsApp account with fake number follow the video link below*👇👇👇👇👇👇👇😈\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/swhK_OfEFNw" },
    { pattern: "*usa number*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n**********************************\n𝗚𝗲𝘁 𝗮 𝗳𝗿𝗲𝗲 𝗳𝗮𝗸𝗲 𝘃𝗶𝗿𝘁𝘂𝗮𝗹 𝗻𝘂𝗺𝗯𝗲𝗿 𝘁𝗼 𝘂𝘀𝗲 𝗶𝗻 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸 𝗮𝗻𝗱 𝗺𝗼𝗿𝗲\n**********************************\n𝗚𝗼 𝘄𝗮𝘁𝗰𝗵 𝗼𝘂𝘁 𝘁𝗵𝗲 𝘃𝗶𝗱𝗲𝗼 𝗮𝗻𝗱 𝗱𝗼𝗻'𝘁 𝗳𝗼𝗿𝗴𝗲𝘁 𝘁𝗼 𝗹𝗶𝗸𝗲 𝘀𝘂𝗯𝘀𝗰𝗿𝗶𝗯𝗲 𝗮𝗻𝗱 𝗵𝗶𝘁 𝗼𝗻 𝗯𝗲𝗹𝗹 𝗶𝗰𝗼𝗻\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/dR4Na1jMN-s" },
    { pattern: "*us number*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n**********************************\n𝗚𝗲𝘁 𝗮 𝗳𝗿𝗲𝗲 𝗳𝗮𝗸𝗲 𝘃𝗶𝗿𝘁𝘂𝗮𝗹 𝗻𝘂𝗺𝗯𝗲𝗿 𝘁𝗼 𝘂𝘀𝗲 𝗶𝗻 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸 𝗮𝗻𝗱 𝗺𝗼𝗿𝗲\n**********************************\n𝗚𝗼 𝘄𝗮𝘁𝗰𝗵 𝗼𝘂𝘁 𝘁𝗵𝗲 𝘃𝗶𝗱𝗲𝗼 𝗮𝗻𝗱 𝗱𝗼𝗻'𝘁 𝗳𝗼𝗿𝗴𝗲𝘁 𝘁𝗼 𝗹𝗶𝗸𝗲 𝘀𝘂𝗯𝘀𝗰𝗿𝗶𝗯𝗲 𝗮𝗻𝗱 𝗵𝗶𝘁 𝗼𝗻 𝗯𝗲𝗹𝗹 𝗶𝗰𝗼𝗻\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/dR4Na1jMN-s" },
    { pattern: "*server*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n**********************************\n𝗖𝗿𝗲𝗮𝘁𝗲 𝘆𝗼𝘂𝗿 𝗼𝘄𝗻 𝘀𝗲𝗿𝘃𝗲𝗿 𝘁𝗼 𝘀𝘂𝗿𝗳 𝗶𝗻𝘁𝗲𝗿𝗻𝗲𝘁 𝗳𝗿𝗲𝗲𝗹𝘆 𝗮𝗰𝗰𝗼𝗿𝗱𝗶𝗻𝗴 𝘁𝗼 𝘆𝗼𝘂𝗿 𝘄𝗮𝘆\n\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/_g4UzbD4nlU" },
    { pattern: "*fake whatsapp*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\nCreate a fake WhatsApp account with fake number follow the video link below\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/swhK_OfEFNw" },
    { pattern: "*hack whatsapp*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽 𝗮𝗰𝗰𝗼𝘂𝗻𝘁 𝗶𝗻 𝘀𝗶𝗺𝗽𝗹𝗲 𝘄𝗮𝘆 𝘄𝗶𝘁𝗵𝗼𝘂𝘁 𝘁𝗼𝘂𝗰𝗵𝗶𝗻𝗴 𝘃𝗶𝗰𝘁𝗶𝗺𝘀 𝗽𝗵𝗼𝗻𝗲 𝘂𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅 🤩🤩\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://fb.watch/cuiRNh3Qoh/" },
    { pattern: "whatsapp hack", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗛𝗮𝗰𝗸 𝗔𝗻𝘆𝗼𝗻𝗲'𝘀 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽 𝗮𝗰𝗰𝗼𝘂𝗻𝘁 𝗶𝗻 𝘀𝗶𝗺𝗽𝗹𝗲 𝘄𝗮𝘆 𝘄𝗶𝘁𝗵𝗼𝘂𝘁 𝘁𝗼𝘂𝗰𝗵𝗶𝗻𝗴 𝘃𝗶𝗰𝘁𝗶𝗺𝘀 𝗽𝗵𝗼𝗻𝗲 𝘂𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅 🤩🤩\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://fb.watch/cuiRNh3Qoh/" },
    { pattern: "*thank you//thnk//tnk//thanks*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n\n𝗪𝗲𝗹𝗰𝗼𝗺𝗲 𝗯𝘂𝗱𝗱𝘆 🤩\n\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝗳𝗼𝗿 𝘀𝘂𝗽𝗽𝗼𝗿𝘁𝗶𝗻𝗴 𝗺𝗲 𝘆𝗼𝘂 𝗮𝗿𝗲 𝗼𝘂𝗿 𝗮𝗹𝗹 𝘁𝗶𝗺𝗲 𝗯𝗲𝘀𝘁 𝘀𝘂𝗯𝘀𝗰𝗿𝗶𝗯𝗲𝗿.\n------------------------------------------------\n𝗧𝗵𝗮𝗻𝗸 𝘆𝗼𝘂 𝘀𝗼 𝗺𝘂𝗰𝗵 𝗳𝗼𝗿 𝘆𝗼𝘂𝗿 𝗹𝗼𝘃𝗲 𝗮𝗻𝗱 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 😊" },
    { pattern: "whatsapp bombing", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗖𝗮𝗹𝗹 𝗮𝗻𝗱 𝗦𝗠𝗦 𝗯𝗼𝗺𝗯𝗶𝗻𝗴 𝗨𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅\nhttps://youtu.be/KM6rISAH2Fw\n********************************\n𝗦𝗲𝗻𝗱 𝗕𝘂𝗹𝗸 𝗪𝗵𝗮𝘁𝘀𝗔𝗽𝗽 𝗕𝗼𝗺𝗯𝗶𝗻𝗴 𝘂𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅\n********************************\nhttps://youtu.be/FyPrhNYTxiM" },
    { pattern: "wordlist", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗚𝗲𝗻𝗲𝗿𝗮𝘁𝗲 𝘆𝗼𝘂𝗿 𝗼𝘄𝗻 𝗪𝗼𝗿𝗱𝗹𝗶𝘀𝘁 𝗶𝗻 𝗧𝗲𝗿𝗺𝘂𝘅 𝗶𝗻 𝟮 𝘀𝗶𝗺𝗽𝗹𝗲 𝘀𝘁𝗲𝗽\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/UOlDFFXz8v4" },
    { pattern: "*instagram followers//instagram follower*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗜𝗻𝗰𝗿𝗲𝗮𝘀𝗲 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗙𝗼𝗹𝗹𝗼𝘄𝗲𝗿𝘀 𝗳𝗿𝗲𝗲 𝗼𝗳 𝗰𝗼𝘀𝘁 𝘄𝗶𝘁𝗵𝗼𝘂𝘁 𝗹𝗼𝗴𝗶𝗻 🤩🤩\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/rcPiD-prtPA" },
    { pattern: "*track location//find location//trace location//live location*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗧𝗿𝗮𝗰𝗸 𝗮𝗻𝘆𝗼𝗻𝗲'𝘀 𝗹𝗶𝘃𝗲 𝗹𝗼𝗰𝗮𝘁𝗶𝗼𝗻 𝘂𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅\n********************************\nType command apt update && apt upgrade\n\nThen type command \n$pkg install git\n\n$pkg install python\n\n$git clone https://github.com/thewhiteh4t/seeker.git\n\n$cd seeker\n\n$ ./termux-install.sh\n\n\nThat's all seeker will be installed in Termux\n\nNow you can run seeker by typing \n$python seeker.py\n\nNow you have to Open New Terminal and type\n\n $./ngrok http 8080\n\n\nYou will get a link as shown in the screenshot (Turn on your hotspot to get the link), so copy the link and send the link to anyone whose location wanna track 😈😈😈😈😈😈" },
    { pattern: "*hello*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n\n𝙃i 𝘿𝙚𝙖𝙧 😀\n𝙒𝙚𝙡𝙘𝙤𝙢𝙚 𝙩𝙤 𝙃𝙖𝙘𝙠𝙚𝙧𝙨 𝘾𝙤𝙡𝙤𝙣𝙮 𝙊𝙛𝙛𝙞𝙘𝙞𝙖𝙡" },
    { pattern: "fb cloning", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗧𝗲𝗿𝗺𝘂𝘅 𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸 𝗜𝗱 𝗖𝗹𝗼𝗻𝗶𝗻𝗴 𝗖𝗼𝗺𝗺𝗮𝗻𝗱\n******************************\n$apt update && apt upgrade\n\n$apt install python2\n\n$apt install git\n\n$git clone https://github.com/htr-tech/haxorbd.git(code-box)\n\n$ls \n\n$cd haxorbd\n\n$python2 haxor.py\n\n\nUSERNAME : haxor \n\nPASSWORD : htrtech" },
    { pattern: "*dark web*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗚𝗲𝘁 𝗮𝗰𝗰𝗲𝘀𝘀 𝘁𝗼 𝗗𝗮𝗿𝗸 𝗪𝗲𝗯 𝘂𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅.𝗜𝘁𝘀 𝗦𝗶𝗺𝗽𝗹𝗲 𝗮𝘀 𝗯𝘂𝘁 𝗯𝗲 𝗮𝘄𝗮𝗿𝗲 𝗼𝗳 𝗗𝗮𝗿𝗸 𝗪𝗲𝗯 𝘁𝗿𝗮𝗽\n*******************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/GxmRQGk_X2g" },
    { pattern: "*ip hack*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n🔰 Auto IP or Domain Attack Tool - IP-Attack on Website Hacking Information Gathering 🔰\n\n♻️ Tools ♻️\n\n✴️ Installation ✴️\n\n$ apt update && apt upgrade\n\n$ apt install git python python2\n\n$ cd $HOME\n\n$ git clone https://github.com/Bhai4You/Ip-Attack\n\n$ cd Ip-Attack\n\n$ chmod +x requirement.sh ip-attack.py\n\n$ bash requirement.sh\n\n$ python2 ip-attack.py\n\nNow enjoying Hacking 😊" },
    { pattern: "*bug bounty*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗕𝘂𝗴 𝗕𝗼𝘂𝗻𝘁𝘆 📱💵💴\n𝗕𝗲 𝗮 𝗠𝗮𝘀𝘁𝗲𝗿 𝗶𝗻 𝗕𝘂𝗴 𝗛𝘂𝗻𝘁𝗶𝗻𝗴 𝗘𝗮𝗿𝗻 𝗠𝗼𝗻𝗲𝘆 𝗹𝗶𝗸𝗲 𝗮 𝗣𝗿𝗼 𝗕𝗲 𝗮 𝗠𝗶𝗹𝗹𝗶𝗼𝗻𝗮𝗶𝗿𝗲\n*******************************\n📣📣Watch Part 1 and Part 2 for better understanding \n😈😈😈😈😈😈😈😈😈\n📣𝗕𝘂𝗴 𝗕𝗼𝘂𝗻𝘁𝘆 Part -1\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/8ICn2KeBzoU\n******************************\n\n📣𝗕𝘂𝗴 𝗕𝗼𝘂𝗻𝘁𝘆 Part -2\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/QI5Yg9PbO6k" },
    { pattern: "*andrax hacking*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗔𝗻𝗱𝗿𝗮𝘅 𝗮 𝗣𝗼𝗿𝘁𝗮𝗯𝗹𝗲 𝗛𝗮𝗰𝗸𝗶𝗻𝗴 𝗠𝗮𝗰𝗵𝗶𝗻𝗲 𝗳𝗼𝗿 𝗔𝗻𝗱𝗿𝗼𝗶𝗱 🤩🤩\n\nWatch video below to know Andrax.......\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/ZFhC9t_rxuc" },
    { pattern: "*recover photos*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗪𝗮𝘁𝗰𝗵 𝘁𝗵𝗲 𝘃𝗶𝗱𝗲𝗼 𝗯𝗲𝗹𝗼𝘄 𝘁𝗼 𝗸𝗻𝗼𝘄 𝗵𝗼𝘄 𝘁𝗼 𝗿𝗲𝗰𝗼𝘃𝗲𝗿 𝗮𝗻𝘆 𝗱𝗲𝗹𝗲𝘁𝗲𝗱 𝗽𝗵𝗼𝘁𝗼𝘀 𝗶𝗻 𝗔𝗻𝗱𝗿𝗼𝗶𝗱 𝗽𝗵𝗼𝗻𝗲 𝘄𝗶𝘁𝗵 𝗷𝘂𝘀𝘁 𝟮 𝘀𝗶𝗺𝗽𝗹𝗲 𝘀𝘁𝗲𝗽𝘀.......\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/iITgUcE3V1I" },
    { pattern: "*free proxy*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n********************************\n𝗪𝗮𝘁𝗰𝗵 𝘁𝗵𝗲 𝘃𝗶𝗱𝗲𝗼 𝗯𝗲𝗹𝗼𝘄 𝘁𝗼 𝗸𝗻𝗼𝘄 𝗵𝗼𝘄 𝘁𝗼 𝗚𝗲𝘁 𝗳𝗿𝗲𝗲 𝗣𝗿𝗼𝘅𝘆 𝗼𝗳 𝗮𝗻𝘆 𝗖𝗼𝘂𝗻𝘁𝗿𝘆 𝗶𝗻 𝗔𝗻𝗱𝗿𝗼𝗶𝗱 𝗽𝗵𝗼𝗻𝗲 𝘂𝘀𝗶𝗻𝗴 𝗧𝗲𝗿𝗺𝘂𝘅.....\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nhttps://youtu.be/p48HTajO38Y" },
    { pattern: "*gand*", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n😡*This is your Last warning⚠️next time if you use abusive words or try to insult or abuse anyone in the group  you will be kicked out of the group and banned permanently*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "*facebook account hacked*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nRecover your Hacked Facebook or Report Fake Facebook Account\nIn easy way.\n********************************\nWatch video to know better👇\nhttps://youtu.be/QHB5FKnSVis" },
    { pattern: "*report facebook*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n\nRecover your Hacked Facebook or Report Fake Facebook Account\nIn easy way.\n********************************\nWatch video to know better👇\nhttps://youtu.be/QHB5FKnSVis" },
    { pattern: "*recover facebook account*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n\nRecover your Hacked Facebook or Report Fake Facebook Account\nIn easy way.\n********************************\nWatch video to know better👇\nhttps://youtu.be/QHB5FKnSVis" },
    { pattern: "install kali linux", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nInstall Kali Linux in Android as Powerful OS to use in without Root.\nAnd enjoying hacking 😈😈😈\n***************************\nhttps://youtu.be/qIrAE8O0QyE" },
    { pattern: "*mod application*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\n\n*Want to get free Mod Application Like Netflix, Amazon Prime,Mod Games and more click on the below link to know how*👇👇👇👇👇👇👇👇\n******************************\nhttps://youtu.be/j-Vd2zGL8NM" },
    { pattern: "whatsapp crashing", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n********************************\n⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬\nWant to destroy or freeze 🥶 someone's Whatsapp. Watch the video below to know how😈\n********************************\nhttps://www.instagram.com/tv/Ccc4nGflJsz/?igshid=YmMyMTA2M2Y=" },
    { pattern: "rat tool", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n********************************\n*Hack Android phone over wan with undetectable RAT*\n\n*Rat Tool Features*😈\n✅ Check SMS\n✅ Check Calls\n✅ Check Contact\n✅ Record Screen\n✅ Live Location Track\n✅ Check WhatsApp\n✅ Monitor Social Acc\n✅ Hack Camera\n✅ Hack Storage\n*With lifetime access 😈And Many more*\nVideo link below 👇👇👇\nhttps://youtu.be/thFhazjd_8c" },
    { pattern: "termux tutorial", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁 🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n*********************************\n*Termux Tutorial watch this full video to learn How to use run and execute tools commands more and become a master in Termux Hacking*\n*********************************\n*Termux Tutorial Part - 1* 🧑‍🏫\n*Video link*  ⬇️⬇️⬇️⬇️⬇️\n\nhttps://youtu.be/UjpvEPvqL2c---------------------------------------------------\n*Termux Tutorial Part - 2* 🧑‍🏫\n*Video link* ⬇️⬇️⬇️⬇️⬇️\n\nhttps://youtu.be/Dj4ncHFrkg0" },
    { pattern: "menu", reply: "*⚡ Type any command below and send. HCO Bot will instantly reply 🤖*\n\n*[ HCO BOT MENU ]*\n\n📸 Camera Hack\n🕸️ Dark Web\n🔢 Otp Bypass\n🔥 Attacks & Exploits\n💣 DDOS Attack\n🔨 Bruteforce Attack\n📸 Instagram Bruteforce\n👥 FB Cloning\n📶 SS7 Attack\n☠️ WhatsApp Virus\n💥 WhatsApp Crash\n💣 WhatsApp Bombing\n📩 SMS Bombing\n📦 Payload\n🦅 Dark Eagle\n💀 Ransomware\n🌐 Hack Website\n\n🛠️ Hacking Tools\n📂 Wordlist\n📂 Wordlist Path\n🧮 Cupp Tool\n🔑 Hydra Tool\n📡 Routersploit\n🕷️ Nikto Tool\n🖲️ USB Rubber Ducky\n🛠️ Tool-X\n📦 Apk Tool\n⚡ Powerful Tool\n\n🌑 Dark Web\n👨‍💻 Hacking Machine\n🆔 Recover Insta Id\n🌐 Website Hack\n🛰️ Info Gathering & OSINT\n🛰️ Info Gathering\n📱 Find Phone\n📍 Hack Location\n🌍 IP Hack\n🎯 Scope Hunter\n⌨️ Key Logger\n📞 Fake Number\n🇺🇸 USA Number\n🌍 Free Proxy\n\n🎮 Game Hacks\n🎮 Bgmi Hack\n🎮 Free Fire Hack\n\n🎓 Learning Zone\n🕶️ Learn Hacking\n💻 Learn Coding\n🎓 Hacking Class\n🎥 Hacking Videos\n👨‍💻 Be a Hacker\n\n📱 Mobile Hacks\n🔥 Wifi Hack\n🐉 Kali Nethunter\n📲 Download Termux\n🖥️ Termux X11\n🛠️ Termux Toolkit\n📖 Termux Tutorial\n📱 Root Android\n📱 Root Termux\n📲 Andrax Hacking\n🔌 Install ADB\n\n💬 Social Media Hacks\n📘 Facebook Hack\n📸 Instagram Hack\n📛 Insta ID Ban\n💬 WhatsApp Hack\n💬 WhatsApp Unban\n⚠️ Report FB Account\n🔓 Recover FB Account\n\n🔗 Others & Extras\n🔗 Hide Link\n🔗 Hacking Link\n📡 Ngrok Masking\n🌐 Install Ngrok\n📧 Fake Email\n📧 Email Bombing\n📱 Virtual Phone\n🖼️ Recover Photos\n⭐ Premium App\n💰 Earn Money Online\n🎬 Video\n🤖 Bot\n🔗 Channel Link\n🚀 Metasploit\n📧 Gmail Hack\n💻 Bug Bounty\n\n━━━━━━━━━━━━━━━━━━━━━━━\n*✨ More options coming soon...*\n*🙏 Thank you*\n*🧑‍💻 Team HCO*\n━━━━━━━━━━━━━━━━━━━━━━━" },
    { pattern: "*port forwarding*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Hey hi Dear😃*\n\n*Watch this video to know how to Port Forwarding in Android For Termux for lifetime without NGROK or Router in 2 easy step 🪜* 😈😈😈\n**********************************-\n*Video link below*👇👇👇👇👇\nhttps://youtu.be/6NzFE_s3gok" },
    { pattern: "*hacking apps*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Hey👋Watch the video below to know some of the Banned app's from playstore and use it for Hacking purposes*\n\n*******************************\n*Video link below 👇👇👇👇*\nhttps://youtu.be/cpg_oj7W2iU" },
    { pattern: "*be a hacker*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Hey hi Dear this is a short video to clear your concepts on how to become a Hacker*\n\n***********************************\n*Video link below 👇👇👇👇*\nhttps://youtu.be/k9bTYNC1J8s" },
    { pattern: "*download termux*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Hey hi Dear watch the video below to know how to update or download Termux in simple easy way from official site*\n\n***********************************\n*Video link below 👇👇👇👇👇*\nhttps://youtu.be/a5jb-viHopw" },
    { pattern: "tool x", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Hey hi Dear watch the video below to know how to install adn run Tool-X tool in Termux just with a simple and easy way*\n\n***********************************\n*Video link below 👇👇👇👇*\nhttps://youtu.be/V8JfmHcCi3A" },
    { pattern: "*sim cloning*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Hey hi Dear, Watch the video below to know how Sim card cloning is done and what hackers do with Sim Card*😈😈😈😈😈😈😈😈😈😈😈😈😈\n\n***********************************\n*Video link below 👇👇👇👇*\nhttps://youtu.be/mUQo2C3jHwE" },
    { pattern: "sms bombing", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Hey hi dear watch the video below to perform sms Bombing 500 sms bomb at one time and prank your friends*\n\n*****************************\"*****\n*Video link below 👇👇👇👇👇*\nhttps://www.instagram.com/tv/Ccc4nGflJsz/?igshid=YmMyMTA2M2Y=" },
    { pattern: "*earn money online*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Hey hi Dear, Wanna Earn Money online sitting at home watch this video to know to earn money online 🤑💰🤑💰🤑💰🤑💰🤑💰🤪\n**********************************\n\n*Video link below 👇👇👇👇👇*\n\nhttps://youtu.be/BRHr50K4BEk" },
    { pattern: "termux tool", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Termux tool is Bunch of tools for Hackers in Termux so go try it out*\n******************************\n*Video link below 👇👇*\n\nhttps://youtu.be/lnCfrutxfgM" },
    { pattern: "Info gathering", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n\n*Watch the tutorial video give below to know how to Gather anyone's Information using Termux*😈😈\n👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/e5_gxM1eQKQ" },
    { pattern: "termux toolkit", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n\nWatch the Tutorial Video given below to know more on Termux Toolkit Tool a God of All tools in Termux 🔥🔥\n👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/uOgpi-o-qG8" },
    { pattern: "hacking link", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the video Tutorial given below to know more on hacking link and how it's perform*😈😈😈😈😈😈\n******************************\n👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/istQKYc1ebw" },
    { pattern: "virtual phone", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the tutorial video given below to know how to Make a Virtual Android on your Phone for Hacking and Testing*\n**********************************\n👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/BqaLJM357CM" },
    { pattern: "*onion sites*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the tutorial video given below to know how an Onion Sites x Dark Web works in Android for Hacking and Testing*\n**********************************\n👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/OJ_x9ZMGxbA" },
    { pattern: "dark eagle", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the tutorial video given below to know how to Run Dark Eagle Tool in Termux*\n**********************************\n👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/g69K-lI4c7A" },
    { pattern: "*nikto tool*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the tutorial video given below to know how to use Nikto Tool in Termux without Root*\n**********************************\n👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/PnS4araiRT4" },
    { pattern: "*email bombing*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the tutorial video given below to know how Perform Email Bombing in Termux Android*\n**********************************\n👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/FytQ_YCir0c" },
    { pattern: "apk tool", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the tutorial video given below to know how install and run Apktool in Termux Android without Root*\n**********************************\n👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/4G1uQQ0fEwc" },
    { pattern: "*Unlimited otp*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the tutorial video given below to know how to avoid getting spam otp or fake otp in your phone number*\n**********************************\n\n👇👇👇👇👇👇👇👇👇👇\nhttps://youtu.be/BKJuwDDcn84" },
    { pattern: "*termux package*", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n***********************************\n*Watch the tutorial video given below to know how to Install all the required Termux packages in 1 go without any complications in Termux*\n**********************************\n\n👇👇👇👇👇👇👇👇👇👇\nhttps://youtu.be/BLYq25x7NCc" },
    { pattern: "metasploit", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n**********************************\n*Install the Most powerful Android Hacking Tool Metasploit in Termux in just 3 min*\n👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/BBT-T33Hf2k" },
    { pattern: "ngrok masking", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n**********************************\n*Hide phishing link under a genuine website to make it look real and hack anyone's info and social media accounts*😈😈😈😈😈😈\n******************************\n\nVideo link below 👇👇\nhttps://youtu.be/nNLS_f8BS88" },
    { pattern: "install adb", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n**********************************\n\n*Install ADB sploit in termux without root and enjoy android debugging*\n******************************\n\nVideo link below 👇👇👇👇\nhttps://youtu.be/mJQuQ4UHku0" },
    { pattern: "scope hunter", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n**********************************\n*Scope Hunter Start your first Bug Bounty Program using Termux*\n**********************************\nVideo link below 👇👇\n\nhttps://youtu.be/w1FF1YoF1Yk" },
    { pattern: "ss7 attack", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n*********************************\n*Wanna know what is SS7 Attack and how it works and how dangerous is it. Go watch out video below to know more 👇👇👇👇👇👇*\n**********************************\nhttps://youtu.be/jU4omNHuIdA" },
    { pattern: "android pentesting", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n*********************************\n*Wanna be an Android Pentester Go watch out the video link given below to know more using Termux* 👇👇\n********************************\nhttps://youtu.be/niyI-LJlnWw" },
    { pattern: "key logger", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n*********************************\nWant to know more about Keylogger how it wors and how dangerous ⚡ is it.\n*********************************\nGo watch out the video given below to know more 🙂🙂👇👇\n\nhttps://youtu.be/Ye-_iAjxIkU" },
    { pattern: "download termux", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n*********************************\n*Click the link below to know how to download Termux without any errors*\n👇👇👇👇👇👇👇\n\nhttps://youtu.be/WxQPb7RaEZg" },
    { pattern: "wifi hack", reply: "𝗜𝗺 𝗛𝗮𝗰𝗸𝗲𝗿𝘀 𝗖𝗼𝗹𝗼𝗻𝘆 𝗕𝗼𝘁🤖\n𝗜𝗺 𝗿𝗲𝗽𝗹𝘆𝗶𝗻𝗴 𝗼𝗻 𝗯𝗲𝗵𝗮𝗹𝗳 𝗼𝗳 𝗔𝗱𝗺𝗶𝗻𝘀.\n👇👇👇👇👇👇👇👇👇👇👇\n*******************************\n*Hack Anyone's WiFi 🧑‍💻📶🛜 just by sending a Link*\n\n*Click the link below to know how*\n👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/Q_OAPNkCPXU" },
    { pattern: "hlo", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n📢*Hope Your Doing Good*😊\n\n*For any kind of help type (menu) and send the message bot will reply u*\n\n*Thank you Team HCO* 🔖" },
    { pattern: "hacking videos", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Top Videos From Hackers Colony on Hacking Tools and Basics Concepts Videos 🤓*\n 🦹🦹🦹🦹🦹🦹🦹🦹🦹🦹\n\n*1.How to Hack Instagram in Termux*👇\nhttps://fb.watch/lMAqqa4bL2/?mibextid=Nif5oz\n\n-------------------------------------\n\n*2.How to Hack Facebook in Termux*👇\nhttps://fb.watch/lMAwUotjsE/?mibextid=Nif5oz\n\n-------------------------------------\n\n*3.How to Run and Install Phonesploit in Termux* 👇\nhttps://fb.watch/lMAZLRICsM/?mibextid=Nif5oz\n\n-------------------------------------\n\n*4. Install and Run Venom Tool in Termux* 👇\nhttps://fb.watch/lMB0_ZYuER/?mibextid=Nif5oz\n\n-------------------------------------\n\n*5.How to Gather anyone's Facebook information using Termux* 👇\nhttps://fb.watch/lMB4mtajvZ/?mibextid=Nif5oz\n\n-------------------------------------\n\n*6.How to Install Metasploit in Termux* 👇\nhttps://fb.watch/lMBjhGPdGq/?mibextid=Nif5oz\n\n-------------------------------------\n\n*7.How to Root Android Phone* 📱👇\nhttps://youtu.be/F52qX6srgyU\n\n-------------------------------------\n\n*8.Bug Bounty In Termux* 👇\nhttps://youtu.be/w1FF1YoF1Yk\n\n-------------------------------------\n\n*9.WhatsApp bombing using Termux* 👇\nhttps://youtu.be/28ZebW9qNY8\n\n-------------------------------------\n\n*10.How to Install Kali Nethunter in Android* 👇\nhttps://youtu.be/yH1HVc523zU\n\n-------------------------------------" },
    { pattern: "rat tool", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Watch the video link given to hack any Android device Using RAT with life time Access* 😈😈\n\n*Video link below 👇👇*\n\nhttps://fb.watch/naFsefQ8EB/?mibextid=Nif5oz" },
    { pattern: "facebook hack", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n--------------------------------------------\n📢📢 *Want to Hack* \n🔥 *Instagram*\n🔥 *Facebook*\n🔥 *Snapchat*\n🔥 *Telegram*\n*And many more do Check out* 👇🏼👇🏼👇🏼\nhttps://youtu.be/_fC0Eju8uMo" },
    { pattern: "ransomware", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Wanna Learn and try how to Destroy anyone's computer or Phone using Ransomware. Must watch the video given* 😈😈\n*******************************\n*Tutorial Link Below 👇👇*\nhttps://youtu.be/JH1XsItFbbs" },
    { pattern: "camera hack", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Hack Anyone's Phone Camera🤳with just by sending a link using Termux* 😈😈\n*******************************\n\n*Check out the Video Tutorial Link Below* 👇\nhttps://youtu.be/EYp0QiQVi6g" },
    { pattern: "hacking tool", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*These are some of the best Advance Hacking tools under Social Engineering for Termux must try* 😈😈🎃🎃\n\nVideo link below 👇👇👇\nhttps://youtu.be/p-clBzzIyy4" },
    { pattern: "find phone", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Find your lost or Stolen Phone using Termux* 😍😍😍\n-------------------------------\n\nVideo link below 👇👇👇\nhttps://youtu.be/UTEfrqzVBB0" },
    { pattern: "social engineering", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Top Advance And Dangerous ⚡ Hacking tool for Termux*\n----------------------------\n\nVideo link below 👇👇👇\nhttps://youtu.be/p-clBzzIyy4" },
    { pattern: "hide link", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Change or Hide Phishing Link in any original Link like google.com*\n\n*To know more watch the video given below 👇👇*\n\nhttps://youtu.be/aKyKYL-GM90" },
    { pattern: "premium app", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n\n*Get premium apps like Netflix Amazon prime YouTube Premium and many more for free*\n\nWatch the video below to know more 👇👇👇\n\nhttps://youtu.be/j-Vd2zGL8NM" },
    { pattern: "whatsapp unban", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n\n*If your WhatsApp account is banned and you want to unban then watch the video link given below to know how to unban WhatsApp account*\n\n👇👇👇👇👇👇\nhttps://youtu.be/lmhm4pCPidU" },
    { pattern: "powerful tool", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n\n*This is one of the most Powerfull Tool that can be run in Termux without Root 😈 so u must try*\n\nVideo link below 👇👇\nhttps://youtu.be/IXdL1x1gpLU" },
    { pattern: "learn hacking", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n\n*Learn Hacking from basics to advance using your Phone via Termux. Termux Hacking Course*\n-------------------------------------------\n*Watch the video below to learn more* 👇👇👇\n*Part -1*\nhttps://youtu.be/UjpvEPvqL2c\n-------------------------------------------\n*Part-2*\nhttps://youtu.be/Dj4ncHFrkg0" },
    { pattern: "usb rubber ducky", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins👬*\n***************************\n\n*How to Make USB Rubber Ducky an advance hacking pendrive to hack bank info system info and More*\n------------------------------------\n*Video link below* 👇👇👇\nhttps://youtu.be/7lDaarWfG-M?si=lqnw47Yrg30__PB0" },
    { pattern: "hack website", reply: "*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins👬*\n***************************\n\n*Guys wanna know how to Hack any Website or get any information using website link or IP Address then do watch the video link given below*\n******************************\n👇👇👇👇👇\n\nhttps://youtu.be/maLmsAfh7S8" },
    { pattern: "hacking class", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins👬*\n----------------------------------------------\n*To Know more about Hacking and To watch our Live Class click on the link below😈😈😈😈😈*\n\n👇👇👇👇👇👇👇👇👇👇\n*Hacking Class Session 1🧑‍🎓*\nhttps://youtube.com/live/4sKiRz7BKXQ?feature=share\n----------------------------------------\n*Hacking Class Session 2🧑‍🎓*\nhttps://youtube.com/live/MBkHWdivjOo?feature=share\n----------------------------------------\n*Hacking Class Session 3🧑‍🎓*\nhttps://youtube.com/live/yhvDA4GKExg?feature=share\n----------------------------------------\n\n*Thank You😊*\n*Team HCO*" },
    { pattern: "password hack", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins👬*\n----------------------------------------\n*To know how a social media accounts password can be hacked and how to be🔐🔑safe and secure from being Getting hacked by Hackers 😈*\n-----------------------------------------\n*Link below 👇 👇 👇*\n\nhttps://youtu.be/lA8s2-Tgj5Y" },
    { pattern: "dm", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot🤖Replying on behalf of the Admins👬*\n------------------------------------------\n*First Warning ⚠️ ⚠️*\n\n*No Dm No Personal Message Whatever you want to ask or share do it in group. but it should be Hacking related only. Anything apart from Hacking and Tech is not allowed*\n\n-----------------------------------------\n*Thank You😊*\n*Team HCO*" },
    { pattern: "personal message", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot🤖Replying on behalf of the Admins👬*\n------------------------------------------\n*First Warning ⚠️ ⚠️*\n\n*No Dm No Personal Message Whatever you want to ask or share do it in group. but it should be Hacking related only. Anything apart from Hacking and Tech is not allowed*\n\n-----------------------------------------\n*Thank You😊*\n*Team HCO*" },
    { pattern: "learn coding", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot🤖Replying on behalf of the Admins👬*\n------------------------------------------\n*Want to learn coding using Smartphone 📲*\n\n*Okay no problem click in the link below to know how* 👇👇👇\n\nhttps://youtu.be/JN6HZvgTlbw?si=qnRbwnyBsBb9FuiW" },
    { pattern: "fake email", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n**************************\nWant Unlimited Free Fake Emails no problem let me show you how to Get it. Click in the link given below to know how* 👇👇👇👇👇\nhttps://youtu.be/_xa02jswUZ4" },
    { pattern: "hydra tool", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n**************************\n*Hydra🔬Tool is one of the most Powerful Bruteforce Tool used by The Hackers😈to Find🔑*\n---------------------------------------\n*Click in the video link below to know how to run and install the Tool*\n👇👇👇👇👇👇👇👇👇\nhttps://youtu.be/I8SPDnT667g" },
    { pattern: "cupp tool", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n*Create a powerful Wordlist or Password list  🔑 using CUPP Tool in Termux💣🔐👨🏼‍💻 to crack any social media account password😈😈*\n👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/gcbkZ9-EWPQ" },
    { pattern: "hacking phone", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n*Want to build your own Hacking Machine your own Hacking Phone 📱 then do watch the video below 👇🏼*\n👇🏼👇🏼\nhttps://youtu.be/XsmHpB_y2yY" },
    { pattern: "wordlist path", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n*Hey HACKERS 😈*\n\n*Having issues how to FIND wordlist Path or Path list in Termux*\n*Then check this out*\n👇🏼👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/pfYxcLDqBfE?si=GsB8d8jbcqoprBNX" },
    { pattern: "zip cracker", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n*Want to Crack any Zip File 🗃️ or Zip Folder 📁 Password then check out this video*\n👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/6_VDrJAJyuE" },
    { pattern: "termux x11", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n*Hey Guys Watch the video below to download the Termux X11 the most advanced and easy way to use Kali Linux or Arch and Many more Hacking Tools without Root*\n👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/hKypVQuA7yk" },
    { pattern: "fake number", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n*Get unlimited disposable numbers using Termux for OTP verification without sign up* 🌟🌟\n👇🏼👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/_xa02jswUZ4" },
    { pattern: "ddos attack", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n\n*Hey Bro You want To freeze or Destroy any website then do try this powerful DDOS tool 🔥🔫*\n\n👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼\nhttps://fb.watch/zbsARZ17C-/" },
    { pattern: "kali nethunter", reply: "hi, hai brother\n\n*I'm Hackers Colony Bot 🤖 Replying on behalf of the Admins*\n***************************\n*If you want to install Kali Nethunter in Termux Android Without root and Get Sudo permission then do watch the video link given below*\n👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/JzIn3655Tl8" },
    { pattern: "location hack", reply: "hi, hai brother\n\n*Now You can Track anyone's Live Location📍🗺️ just by sending a Link 🔗👨🏼‍💻*\n*Check the video below 👇🏼*\n👇🏼👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/thFhazjd_8c" },
    { pattern: "free fire hack", reply: "hi, hai brother\n\n*🫵🏼🫵🏼Now you can Hack Free Fire Game Account just by sending a Link 🖇️👨🏼‍💻*\n\n*Do check out 👇🏼👇🏼*\nhttps://youtu.be/d3phSxOgMRo" },
    { pattern: "insta id ban", reply: "hi, hai brother\n\n*Learn how to Report and ban Instagram id Permanently using Termux 🎯👨🏼‍💻🎩*\n\n👇🏼👇🏼👇🏼👇🏼\nhttps://youtu.be/NEyK-4Mv8Ac?si=-Tw3SmSLkJDoQhEx" },
    { pattern: "bgmi hack", reply: "hi, hai brother\n\n*If you are looking on how to Hack PUBG BGMI 🎮 🎯 Account then check out the video below*\n👇🏼👇🏼👇🏼👇🏼👇🏼👇🏼\n\nhttps://youtu.be/0vUr4Ex6B1E" },
    { pattern: "nethunter", reply: "*Install Kali Nethunter 2025 in Android Termux (Without Root) in simple easy way*\n\n*Check out the video*\n👇👇👇\nhttps://youtu.be/5Aiah61DMqI" },
    { pattern: "dark web", reply: "hi, hai brother\n\n*Check out the video link below to know about top 5 WEBSITE where u can get the Dark Web 🕸️ 🔗 link*\n👨‍💻🔓✨🎉\n👇👇👇👇👇👇\nhttps://youtube.com/shorts/NYgZdFB3yNI?feature=share" },
    { pattern: "website hack", reply: "hi, hai brother\n\n*Hack any Website using Termux in just simple and easy way using our Tool* 🔥 📱 \n👇👇👇👇👇👇\nhttps://youtu.be/ZRtfxVjl-3s?si=5w7tZmwQ8hg-c60S" },
    { pattern: "recover insta id", reply: "hi, hai brother\n\n*Is your Instagram ID got banned or Disabled 😞. Don't worry we have found a new way follow that and u can get your Instagram ID back 🆔*\n \n*Check out he video below 👇 👇*\nhttps://youtu.be/HMzFTsRsN94" },
    { pattern: "hacking machine", reply: "hi, hai brother\n\n*Wants to Turn you Phone 📱 into a Ethical Hacking Machine and start Ethical Hacking 👨‍💻*\n\n*Then Check out this video*\n👇👇👇\nhttps://youtu.be/uJ4v6jZYcdo" },
    { pattern: "dark web", reply: "hi, hai brother\n\n*🔍 Check whether your Email ✉️, Phone Number 📱, or Password 🔑 has been exposed in a data breach or leaked on the Dark Web 🌑*\n\n*Check out 👇*\nhttps://youtu.be/LDu8Vpcw2Ec?si=Xhn02ytjBRCmIvI-" }
];

// ------------------- UTILITY FUNCTIONS -------------------
function matchesPattern(message, pattern) {
    // Convert pattern to regex
    // If pattern contains '//', split and treat as OR
    if (pattern.includes('//')) {
        const parts = pattern.split('//');
        return parts.some(part => matchesPattern(message, part));
    }
    // Escape regex special characters except '*'
    let regexStr = pattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // Replace '*' with '.*' for wildcard
    regexStr = regexStr.replace(/\*/g, '.*');
    // Case insensitive
    const regex = new RegExp(`^${regexStr}$`, 'i');
    return regex.test(message);
}

function findMatchingRule(message) {
    for (const rule of rules) {
        if (matchesPattern(message, rule.pattern)) {
            return rule;
        }
    }
    return null;
}

// ------------------- BOT LOGIC -------------------
const question = (text) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    return new Promise((resolve) => rl.question(text, (answer) => {
        rl.close();
        resolve(answer);
    }));
};

async function startBot() {
    const { state, saveCreds } = await useMultiFileAuthState('auth_info');
    const { version } = await fetchLatestBaileysVersion();

    const sock = makeWASocket({
        version,
        auth: {
            creds: state.creds,
            keys: makeCacheableSignalKeyStore(state.keys, pino({ level: "silent" })),
        },
        printQRInTerminal: false,
        logger: pino({ level: "silent" }),
        browser: ["Ubuntu", "Chrome", "20.0.04"]
    });

    if (!sock.authState.creds.registered) {
        console.log("Waiting for connection to be ready...");
        const phoneNumber = await question('Apna WhatsApp Number (With Country Code) daalein: ');
        setTimeout(async () => {
            try {
                let code = await sock.requestPairingCode(phoneNumber);
                code = code?.match(/.{1,4}/g)?.join("-") || code;
                console.log(`\n\x1b[1m\x1b[33mTERI PAIRING CODE:\x1b[0m \x1b[1m\x1b[32m${code}\x1b[0m\n`);
            } catch (err) {
                console.error("Pairing Error:", err);
            }
        }, 6000);
    }

    sock.ev.on('connection.update', async (update) => {
        const { connection, lastDisconnect } = update;

        if (connection === 'close') {
            let reason = new Boom(lastDisconnect?.error)?.output.statusCode;
            if (reason !== DisconnectReason.loggedOut) {
                startBot();
            } else {
                console.log("Session Expired. Delete auth_info and try again.");
                process.exit();
            }
        } else if (connection === 'open') {
            console.log('\n\x1b[32m[CONNECTED] Bot ab chal raha hai!\x1b[0m');
        }
    });

    sock.ev.on('creds.update', saveCreds);

    // ------------------- MESSAGE HANDLER -------------------
    sock.ev.on('messages.upsert', async (m) => {
        const msg = m.messages[0];
        if (!msg.message) return;

        // Ignore messages sent by the bot itself (optional)
        // if (msg.key.fromMe) return;

        const textMessage = msg.message.conversation ||
                            msg.message.extendedTextMessage?.text ||
                            msg.message.imageMessage?.caption ||
                            msg.message.videoMessage?.caption ||
                            '';

        if (!textMessage) return;

        const rule = findMatchingRule(textMessage);
        if (rule) {
            // Replace placeholders (simple for now)
            let reply = rule.reply;
            // Optionally replace hi, %name% etc. We'll just send as is.
            // Could extract sender name if needed.
            await sock.sendMessage(msg.key.remoteJid, { text: reply }, { quoted: msg });
        }
    });
}

startBot();
